name: Node CI - Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build, and test
      run: |
        yarn
        yarn build
        yarn build-storybook
        yarn test
        yarn chroma test --app-code=${{ secrets.CHROMA_APP_CODE }} --exit-zero-on-changes
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    #- name: Skip CI
    #  uses: veggiemonk/skip-commit@master
    #  env:
    #    COMMIT_FILTER: skip ci
    - name: Prepare repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git checkout master
        git remote rm origin
        git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin
        git branch --set-upstream-to origin/master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git remote -v
        #yarn
        #yarn build
        #yarn build-storybook
        #yarn test
        #yarn chroma test --app-code=${{ secrets.CHROMA_APP_CODE }} --exit-zero-on-changes
        yarn release
