name: Node CI - Release

on: 
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git remote rm origin
        git remote add origin "https://$GH_TOKEN@github.com/lindgr3n/lindgr3n-design-system.git"
        git fetch origin
        git branch --set-upstream-to origin/master
    - name: install, build, and test
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
      run: |
        yarn
        yarn build
        yarn build-storybook
        yarn test
        yarn chromatic test --app-code=${{ secrets.CHROMATIC_APP_CODE }} --exit-zero-on-changes
        yarn release
